version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --with docs
  commands:
    - sphinx-apidoc -f -o docs/source pykinect_recorder

sphinx:
  fail_on_warning: true
  configuration: docs/source/conf.py
